### PR TITLE
Qualify endl, dec, hex with Qt namespace

### PR DESCRIPTION
**Pull request by gruenich**
Qualify `endl`, `dec`, `hex` by using `Qt::endl`, `Qt::dec`, `Qt::hex`.
Qt 6 does not support the old form.

### CODE REVIEW

**Comment by shundhammer** [comment]
Well, I know that they did this for Qt 6, and it pisses me off to no end: Now I have to write `Qt::endl` instead of just `endl` for every damn logging line, and that makes logging a PITA.

That was also the main point the kept me from porting QDirStat to Qt 6: It just makes everyday life a PITA for the developers. I am still thinking about rewriting my whole logger rather than giving up to their outstretched middle finger that they show me with this. I just don't know yet how to go about this.

All attempts to make this BS usable for normal humans failed: No `using Qt::endl`, no `#define ` orgies; nothing helped.

I even have an abandoned experimental branch around with a `std::ostream` based logger, but that failed miserably because now gcc complains about ambiguous type conversions with `std::string` vs. `QString` vs. `const char *`, all of which I want to write to a log stream, of course. And `std::ostream` of course knows how to write a `std::string`, and adding an `operator<<( const QString & )` introduces that ambiguity where now gcc smugly tells me that "hey, we'd know how to handle that, but that C++ 17 standard demands that we throw a warning about it". Just great.

For an alternative logger, the crucial point is that chaining log output with `logDebug() << myqstring << "my message"` needs something final to flush the output buffer so it appears in the log when I follow it with `tail -F`, and it gets flushed when something crashes.

I wrote many different loggers over the last decades, and with stream output I was glad that I finally didn't need a `printf()` like format string anymore; and now they messed that up with their `Qt::endl`. And I don't yet know how to write my own custom stream manipulator that ends the line and flushes the buffer; how exactly the stream manipulators interact with the stream.

So, until Qt 6 is a really urgent thing and I can no longer delay this annoyance, this is on hold. I have some hopes for a better solution than giving in to the Trolls' `Qt::endl` thing.

**Comment by gruenich** [comment]
I was not aware that some get so emotionally over typing for characters. ;-)

I created #27 to demonstrate a Qt 6 move is immanent. It would be helpful to get this pull request merged, as it easly causes merge request due to its sheer size.

**Comment by shundhammer** [comment]
Did the `Qt::hex` / `Qt::dec` part manually.

**Comment by gruenich** [comment]
I would have appreciated a cherry-pick. Never mind.

**Comment by shundhammer** [comment]
So would I, but it already had conflicts.

**Pull request closed without merging**
