### PR TITLE
Replace most QRegExp

### PR DESCRIPTION
**Pull request by gruenich**
I am unsure if all changes are correct. There are no automated tests and the application crashes on start-up. Having regular expression code just compiling is weak.

Preparation of port to Qt 6.

### CODE REVIEW

**Comment by shundhammer** [comment]
First I checked if we need those regexps at all; the overloaded `showChangesDialog( ..., QRegExp, ... )` looked suspicious to me, something overengineered that we might be able to drop. But sadly, not, there are some methods in `YQPkgSelector` that add matching `-devel` or `-debuginfo` etc. packages to a package, and that's where that variant is used.

But my gut feeling is that the empty regexps might be the problem. It might be as simple as using the default constructor for a `QRegularExpression()`.

BTW the `zypp.log` should have a backtrace.

**Comment by shundhammer** [comment]
I just checked out your branch and built it, and it doesn't crash for me; neither with `src/yqpkg --fake-root --fake-commit` nor with `sudo src/yqpkg`.

So let's try to merge it. LGTM anyway.

**Review by shundhammer — APPROVED** [review]
LGTM

**Comment by shundhammer** [comment]
No problem, works as expected. With `--fake-root --fake-commit` I added `Mesa-demo` from PackMan which adds some dependencies, and that changes dialog appeared as it should. I could switch from "Automatic changes" to "User" and to "All", and it worked.

Then I selected "Add matching -debuginfo packages" from the menu, and that dialog worked well again (except that it shows automatic changes initially, and those -debuginfo are selected as user, so they don't show up until you switch to "User" or "All").

Mabe you experienced a fluke, and your `build/` subdirectory just contained something weird. Or maybe there is a completely different problem still hidden somewhere deep; it doesn't need to be connected with this `QRegExp` vs. `QRegularExpression` change.

**Comment by gruenich** [comment]
I verified it is not this merge request, crash happened always, see #32

**Pull request merged**
